"""initial schema

Revision ID: e85a92de33a0
Revises: 
Create Date: 2026-08-29 16:12:12.786475+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85a92de33a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_time', 'audit_log', ['action', 'timestamp'], unique=False)
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('commitments', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('deal_size', sa.Float(), nullable=True),
    sa.Column('urgency', sa.String(length=10), nullable=False),
    sa.Column('conversation_date', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conv_ingested', 'conversations', ['ingested_at'], unique=False)
    op.create_index('ix_conv_source', 'conversations', ['source'], unique=False)
    op.create_index('ix_conv_urgency', 'conversations', ['urgency'], unique=False)
    op.create_table('followup_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('prospect_name', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('variant_agreeable', sa.Text(), nullable=False),
    sa.Column('variant_direct', sa.Text(), nullable=False),
    sa.Column('variant_soft', sa.Text(), nullable=False),
    sa.Column('selected_variant', sa.String(length=20), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('send_status', sa.String(length=20), nullable=True),
    sa.Column('to_address', sa.String(length=200), nullable=True),
    sa.Column('opens', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_draft_sent', 'followup_drafts', ['sent'], unique=False)
    op.create_index(op.f('ix_followup_drafts_conversation_id'), 'followup_drafts', ['conversation_id'], unique=False)
    op.create_table('scored_prospects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('recency_days', sa.Float(), nullable=False),
    sa.Column('engagement_probability', sa.Float(), nullable=False),
    sa.Column('deal_value_normalized', sa.Float(), nullable=False),
    sa.Column('urgency_score', sa.Float(), nullable=False),
    sa.Column('sla_deadline', sa.DateTime(), nullable=False),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.Column('times_requeued', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_status', sa.String(length=20), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.Column('last_action_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scored_prospects_conversation_id'), 'scored_prospects', ['conversation_id'], unique=False)
    op.create_index('ix_sp_score', 'scored_prospects', ['priority_score'], unique=False)
    op.create_index('ix_sp_sla', 'scored_prospects', ['sla_deadline'], unique=False)
    op.create_index('ix_sp_status', 'scored_prospects', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sp_status', table_name='scored_prospects')
    op.drop_index('ix_sp_sla', table_name='scored_prospects')
    op.drop_index('ix_sp_score', table_name='scored_prospects')
    op.drop_index(op.f('ix_scored_prospects_conversation_id'), table_name='scored_prospects')
    op.drop_table('scored_prospects')
    op.drop_index(op.f('ix_followup_drafts_conversation_id'), table_name='followup_drafts')
    op.drop_index('ix_draft_sent', table_name='followup_drafts')
    op.drop_table('followup_drafts')
    op.drop_index('ix_conv_urgency', table_name='conversations')
    op.drop_index('ix_conv_source', table_name='conversations')
    op.drop_index('ix_conv_ingested', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_index('ix_audit_action_time', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
